// frontend/src/routes/TopicResearch.tsx
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
  Cell,
} from 'recharts'
import { api } from '../lib/api'
import {
  Search,
  Loader2,
  Target,
  Copy,
  Check,
  TrendingUp,
  TrendingDown,
  Minus,
  Sparkles,
} from 'lucide-react'

interface TopicAnalysis {
  topic: string
  verdict: string
  scores: { opportunity: number; competition: number; keyword_score: number }
  volume: string
  demand: { serp_total: number; avg_views_per_ranking_video: number; actively_published: boolean }
  gap: { score: number; type: string; demand_views: number; supply_videos: number }
  ranking_chart: { position: number; title: string; channel: string; views: number; seo_score: number }[]
  packaging: { title: string; description: string; tags: string[] }
  suggested_tags: { tag: string; usage: number }[]
  related_keywords: { keyword: string; popularity_rank: number }[]
}

function fmtViews(v: number) {
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(1)}M`
  if (v >= 1_000) return `${(v / 1_000).toFixed(0)}k`
  return String(v)
}

export default function TopicResearch() {
  const [input, setInput] = useState('')
  const [topic, setTopic] = useState('')
  const [copied, setCopied] = useState(false)

  const { data, isLoading, error } = useQuery({
    queryKey: ['topicAnalysis', topic],
    queryFn: () => api.analysisTopic(topic),
    enabled: topic.length > 0,
  })

  const analysis = data as TopicAnalysis | undefined

  const runAnalysis = () => {
    const t = input.trim()
    if (t) setTopic(t)
  }

  const copyAll = async () => {
    if (!analysis) return
    const bundle = [
      `TITLE: ${analysis.packaging.title}`,
      '',
      'DESCRIPTION:',
      analysis.packaging.description,
      '',
      'TAGS:',
      analysis.packaging.tags.join(', '),
    ].join('\n')
    await navigator.clipboard.writeText(bundle)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const chartData = (analysis?.ranking_chart ?? []).map((r) => ({
    name: `#${r.position} ${r.channel}`.slice(0, 22),
    views: r.views,
    seo: Math.round(r.seo_score),
  }))

  const verdictIcon = (v: string) => {
    if (v === 'rising') return <TrendingUp size={14} className="text-green-400" />
    if (v === 'falling') return <TrendingDown size={14} className="text-red-400" />
    return <Minus size={14} className="text-gray-400" />
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2">
        <Sparkles size={20} className="text-accent" />
        <h1 className="text-2xl font-bold">Topic Research</h1>
      </div>
      <p className="text-sm text-gray-500 -mt-3">
        Enter a topic you want to make a video about. TubeForge scans YouTube in realtime, finds the
        demand-supply gap, and drafts precise title/description/tags to help you rank.
      </p>

      {/* Topic input */}
      <div className="flex gap-2">
        <div className="relative flex-1">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" />
          <input
            type="text"
            placeholder="e.g. rust async tokio, system design load balancer, ..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && runAnalysis()}
            className="w-full pl-9 pr-3 py-2.5 bg-surface border border-border rounded-lg text-sm focus:outline-none focus:border-accent"
          />
        </div>
        <button
          onClick={runAnalysis}
          disabled={isLoading || !input.trim()}
          className="px-4 py-2.5 rounded-lg bg-accent/15 border border-accent/30 text-sm font-semibold text-accent hover:bg-accent/25 disabled:opacity-50 transition-colors"
        >
          {isLoading ? <Loader2 size={14} className="animate-spin inline" /> : 'Analyze'}
        </button>
      </div>

      {isLoading && (
        <div className="p-12 flex justify-center text-gray-500">
          <Loader2 size={20} className="animate-spin mr-2" /> Scanning YouTube for "{topic}"...
        </div>
      )}

      {error && (
        <div className="rounded-xl bg-red-500/10 border border-red-500/30 p-4 text-sm text-red-400">
          Analysis failed. Make sure yt-dlp is enabled (TUBEFORGE_YTDLP_ENABLED=true).
        </div>
      )}

      {analysis && (
        <>
          {/* Verdict + scores */}
          <div className={`rounded-xl p-4 border flex items-start gap-3 ${
            analysis.scores.opportunity >= 70 ? 'border-green-500/30 bg-green-500/10' :
            analysis.scores.opportunity >= 40 ? 'border-yellow-500/30 bg-yellow-500/10' :
            'border-border bg-surface'
          }`}>
            <Target size={18} className="mt-0.5 shrink-0 text-accent" />
            <div className="text-sm">
              <div className="font-semibold capitalize flex items-center gap-1.5">
                {verdictIcon(analysis.verdict)} {analysis.verdict} demand
              </div>
              <div className="text-gray-400 mt-1">{analysis.gap.type}</div>
            </div>
            <div className="ml-auto flex gap-4 text-xs">
              <div className="text-center">
                <div className="text-gray-500">Opportunity</div>
                <div className="font-bold text-lg">{analysis.scores.opportunity.toFixed(0)}</div>
              </div>
              <div className="text-center">
                <div className="text-gray-500">Competition</div>
                <div className="font-bold text-lg">{analysis.scores.competition.toFixed(0)}</div>
              </div>
              <div className="text-center">
                <div className="text-gray-500">Volume</div>
                <div className="font-bold text-lg capitalize">{analysis.volume.toLowerCase()}</div>
              </div>
            </div>
          </div>

          {/* Ranking chart */}
          <div className="rounded-xl bg-surface border border-border p-4">
            <h2 className="text-sm font-medium text-gray-400 mb-3">What ranks now (top videos by views)</h2>
            <ResponsiveContainer width="100%" height={240}>
              <BarChart data={chartData} layout="vertical" margin={{ top: 4, right: 8, bottom: 0, left: 8 }}>
                <CartesianGrid stroke="#2a2f3a" horizontal={false} />
                <XAxis type="number" tick={{ fill: '#9ca3af', fontSize: 11 }} tickFormatter={(v: number) => fmtViews(v)} />
                <YAxis type="category" dataKey="name" tick={{ fill: '#9ca3af', fontSize: 10 }} width={120} />
                <Tooltip contentStyle={{ background: '#1a1a1a', border: '1px solid #333', borderRadius: 8, color: '#fff' }} />
                <Bar dataKey="views" radius={[0, 3, 3, 0]}>
                  {chartData.map((_, i) => (
                    <Cell key={i} fill={i === 0 ? '#4f8cff' : '#3b82f6'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* Packaging */}
          <div className="rounded-xl bg-surface border border-border p-4">
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-sm font-medium text-gray-400">Recommended packaging for your video</h2>
              <button
                onClick={copyAll}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface border border-border text-xs font-medium hover:border-accent/50 hover:text-gray-200 transition-colors"
              >
                {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
                {copied ? 'Copied' : 'Copy all'}
              </button>
            </div>
            <div className="text-lg font-bold text-accent mb-3">{analysis.packaging.title}</div>
            <p className="text-sm text-gray-300 whitespace-pre-wrap mb-4">{analysis.packaging.description}</p>
            <div className="flex flex-wrap gap-1.5">
              {analysis.packaging.tags.map((t) => (
                <span key={t} className="px-2 py-1 rounded-full bg-accent/10 border border-accent/25 text-xs text-accent">{t}</span>
              ))}
            </div>
          </div>

          {/* Suggested + related */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="rounded-xl bg-surface border border-border p-4">
              <h2 className="text-sm font-medium text-gray-400 mb-3">Tags harvested from ranking videos</h2>
              <div className="flex flex-wrap gap-1.5">
                {analysis.suggested_tags.map((t) => (
                  <span key={t.tag} className="px-2 py-1 rounded-full bg-gray-800/60 border border-border text-xs text-gray-300" title={`Used by ${t.usage} ranking videos`}>
                    {t.tag}
                    <span className="ml-1 text-[10px] text-gray-500">×{t.usage}</span>
                  </span>
                ))}
              </div>
            </div>
            <div className="rounded-xl bg-surface border border-border p-4">
              <h2 className="text-sm font-medium text-gray-400 mb-3">Related keywords (autocomplete)</h2>
              <div className="flex flex-wrap gap-1.5">
                {analysis.related_keywords.slice(0, 15).map((r) => (
                  <button
                    key={r.keyword}
                    onClick={() => { setInput(r.keyword); setTopic(r.keyword) }}
                    className="px-2 py-1 rounded-full bg-gray-800/60 border border-border text-xs text-gray-300 hover:border-accent/40 transition-colors"
                  >
                    {r.keyword}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  )
}

// frontend/src/routes/TopicResearch.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { rpc } from '../lib/rpc.svelte';
  import { 
    Search, 
    Sparkles, 
    Kanban, 
    Check, 
    Clock, 
    TrendingUp, 
    Flame, 
    FileText,
    ExternalLink,
    Cpu,
    Radio,
    Tag,
    Copy,
    BarChart3,
    AlertCircle,
    Layers,
    Eye,
    Award,
    Smartphone,
    ShieldCheck,
    CheckCircle2,
    Sliders
  } from 'lucide-svelte';
  import VideoAnalyticsModal from '../components/VideoAnalyticsModal.svelte';

  interface RankingVideo {
    position: number;
    title: string;
    channel: string;
    views: number;
    seo_score: number;
    video_id?: string;
  }

  interface SuggestedTag {
    tag: string;
    usage: number;
  }

  interface RelatedKeyword {
    keyword: string;
    popularity_rank: number;
  }

  interface TitleVariation {
    archetype: string;
    title: string;
    mobile_preview_45: string;
    rationale: string;
  }

  interface TopicAnalysisResponse {
    topic: string;
    volume: string;
    verdict: string;
    scores: {
      opportunity: number;
      competition: number;
      keyword_score: number;
    };
    demand: {
      actively_published: boolean;
      avg_views_per_ranking_video: number;
      serp_total: number;
    };
    gap: {
      demand_views: number;
      score: number;
      supply_videos: number;
      type: string;
    };
    packaging: {
      title: string;
      title_variations?: TitleVariation[];
      mobile_preview_45?: string;
      description: string;
      tags: string[];
      has_colon?: boolean;
      char_count?: number;
    };
    ranking_chart: RankingVideo[];
    related_keywords: RelatedKeyword[];
    suggested_tags: SuggestedTag[];
  }

  let query = $state('');
  let serpLimit = $state(8);
  let loading = $state(false);
  let research = $state<TopicAnalysisResponse | null>(null);
  let selectedTitle = $state<string>('');
  let createdTicketMessage = $state<string | null>(null);
  let activeTab = $state<'packaging' | 'variations' | 'serp' | 'keywords'>('packaging');
  let selectedVideoId = $state<string | null>(null);
  let copiedText = $state<string | null>(null);

  let { 
    initialQuery = '', 
    onNavigate 
  }: { 
    initialQuery?: string; 
    onNavigate?: (route: string, param?: string) => void 
  } = $props();

  onMount(() => {
    if (initialQuery && initialQuery.trim()) {
      query = initialQuery;
      handleSearch();
    } else {
      query = 'Rust Async Tokio Web Development';
      handleSearch();
    }
  });

  async function handleSearch() {
    if (!query.trim()) return;
    loading = true;
    createdTicketMessage = null;
    try {
      const res = await fetch(`/api/analysis/topic?q=${encodeURIComponent(query.trim())}&serp=${serpLimit}`);
      if (res.ok) {
        research = await res.json();
        if (research?.packaging?.title) {
          selectedTitle = research.packaging.title;
        }
      }
    } catch {
      // ignore
    } finally {
      loading = false;
    }
  }

  async function createKanbanTicket(titleToUse?: string) {
    if (!research) return;
    const finalTitle = titleToUse || selectedTitle || research.packaging.title;
    try {
      const res = await rpc.call('kanban.from-research', {
        topic: finalTitle,
        channel: 'TECHVERSE',
        framework: 'Core Mental Model',
        optimal_duration_sec: 720,
      });
      if (res && res.message) {
        createdTicketMessage = res.message;
      }
    } catch (e: any) {
      createdTicketMessage = `Error creating ticket — ${e.message}`;
    }
  }

  function copyToClipboard(text: string) {
    navigator.clipboard.writeText(text);
    copiedText = text;
    setTimeout(() => copiedText = null, 1500);
  }
</script>

<div class="space-y-6">

  <!-- Search Header -->
  <div class="p-6 rounded-2xl bg-gray-900/60 border border-gray-800 space-y-4">
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
      <div>
        <h2 class="text-xl font-extrabold text-white tracking-tight flex items-center space-x-2">
          <span>Topic Intelligence & Empirical Packaging Engine</span>
        </h2>
        <p class="text-xs text-gray-400">
          Zero-colon architecture, 45-character mobile viewport optimization, and 4 empirical title archetypes.
        </p>
      </div>
    </div>

    <!-- Search Bar -->
    <form onsubmit={(e) => { e.preventDefault(); handleSearch(); }} class="flex flex-col sm:flex-row gap-2">
      <div class="relative flex-1">
        <Search class="w-4 h-4 text-gray-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
        <input 
          type="text" 
          bind:value={query}
          placeholder="Enter developer topic (e.g. Linux Kernel Syscalls, SQLite Internals, Rust Async)..."
          class="w-full pl-10 pr-4 py-2.5 rounded-xl bg-gray-950 border border-gray-800 text-gray-100 placeholder-gray-500 text-sm focus:outline-none focus:border-indigo-500/80 transition-colors"
        />
      </div>

      <button
        type="submit"
        disabled={loading}
        class="px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white text-xs font-bold shadow-lg shadow-indigo-500/20 transition-all flex items-center justify-center space-x-2 cursor-pointer"
      >
        {#if loading}
          <span class="animate-spin w-4 h-4 border-2 border-white border-t-transparent rounded-full"></span>
          <span>Analyzing SERP...</span>
        {:else}
          <Sparkles class="w-4 h-4" />
          <span>Analyze & Package</span>
        {/if}
      </button>
    </form>
  </div>

  {#if research}
    
    <!-- Topic Overview & Action Banner -->
    <div class="p-5 rounded-2xl bg-gray-900/60 border border-gray-800 space-y-4">
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
        
        <div class="space-y-1">
          <div class="flex items-center space-x-2.5">
            <span class="text-lg font-extrabold text-white">
              "{research.topic}"
            </span>
            <span class="px-2.5 py-0.5 rounded-full text-xs font-mono font-bold bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
              {research.volume} Volume
            </span>
            <span class="px-2 py-0.5 rounded-full text-[10px] font-mono font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 flex items-center space-x-1">
              <CheckCircle2 class="w-3 h-3" />
              <span>Zero Colons Verified</span>
            </span>
          </div>
          <p class="text-xs text-gray-400 max-w-3xl">
            {research.verdict}
          </p>
        </div>

        <!-- Quick Action Buttons -->
        <div class="flex items-center space-x-2 shrink-0">
          <button
            type="button"
            onclick={() => createKanbanTicket()}
            class="inline-flex items-center space-x-1.5 px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold shadow-lg shadow-indigo-500/20 transition-all cursor-pointer"
          >
            <Kanban class="w-3.5 h-3.5" />
            <span>Send Selected to Kanban</span>
          </button>

          {#if onNavigate}
            <button
              type="button"
              onclick={() => onNavigate('teleprompter')}
              class="inline-flex items-center space-x-1.5 px-3.5 py-2 rounded-xl bg-gray-800 hover:bg-gray-750 text-gray-200 text-xs font-medium transition-all cursor-pointer"
            >
              <Radio class="w-3.5 h-3.5 text-purple-400" />
              <span>Open in Teleprompter</span>
            </button>
          {/if}
        </div>

      </div>

      {#if createdTicketMessage}
        <div class="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs flex items-center justify-between">
          <span>{createdTicketMessage}</span>
          {#if onNavigate}
            <button 
              type="button"
              onclick={() => onNavigate('kanban')}
              class="underline font-semibold hover:text-white cursor-pointer"
            >
              View on Kanban Board →
            </button>
          {/if}
        </div>
      {/if}

      <!-- Metric Score Cards Grid -->
      <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2">
        
        <div class="p-3.5 rounded-xl bg-gray-950/80 border border-gray-800 space-y-1">
          <span class="text-[10px] font-mono text-gray-400 uppercase tracking-wider block">Opportunity Score</span>
          <div class="text-xl font-extrabold text-emerald-400 font-mono">
            {research.scores.opportunity.toFixed(1)} <span class="text-xs text-gray-500 font-normal">/ 100</span>
          </div>
          <span class="text-[10px] text-gray-500 block">Demand vs Competition Ratio</span>
        </div>

        <div class="p-3.5 rounded-xl bg-gray-950/80 border border-gray-800 space-y-1">
          <span class="text-[10px] font-mono text-gray-400 uppercase tracking-wider block">Competition Score</span>
          <div class="text-xl font-extrabold text-amber-400 font-mono">
            {research.scores.competition.toFixed(1)} <span class="text-xs text-gray-500 font-normal">/ 100</span>
          </div>
          <span class="text-[10px] text-gray-500 block">SERP Saturation Barrier</span>
        </div>

        <div class="p-3.5 rounded-xl bg-gray-950/80 border border-gray-800 space-y-1">
          <span class="text-[10px] font-mono text-gray-400 uppercase tracking-wider block">Avg Ranking Views</span>
          <div class="text-xl font-extrabold text-purple-400 font-mono">
            {Math.round(research.demand.avg_views_per_ranking_video).toLocaleString()}
          </div>
          <span class="text-[10px] text-gray-500 block">Average views of Top SERP</span>
        </div>

        <div class="p-3.5 rounded-xl bg-gray-950/80 border border-gray-800 space-y-1">
          <span class="text-[10px] font-mono text-gray-400 uppercase tracking-wider block">Market Gap Signal</span>
          <div class="text-xs font-bold text-indigo-300 font-mono truncate">
            {research.gap.type}
          </div>
          <span class="text-[10px] text-gray-500 block">Strategy Recommendation</span>
        </div>

      </div>

    </div>

    <!-- Navigation Tabs -->
    <div class="flex space-x-2 border-b border-gray-800 pb-1">
      <button
        type="button"
        onclick={() => activeTab = 'packaging'}
        class="px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer {
          activeTab === 'packaging' 
            ? 'bg-indigo-600 text-white shadow-md shadow-indigo-500/10' 
            : 'text-gray-400 hover:text-gray-200 hover:bg-gray-850'
        }"
      >
        Live Packaging & Mobile Viewport
      </button>

      <button
        type="button"
        onclick={() => activeTab = 'variations'}
        class="px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer {
          activeTab === 'variations' 
            ? 'bg-indigo-600 text-white shadow-md shadow-indigo-500/10' 
            : 'text-gray-400 hover:text-gray-200 hover:bg-gray-850'
        }"
      >
        4 Research Archetypes ({research.packaging?.title_variations?.length || 4})
      </button>

      <button
        type="button"
        onclick={() => activeTab = 'serp'}
        class="px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer {
          activeTab === 'serp' 
            ? 'bg-indigo-600 text-white shadow-md shadow-indigo-500/10' 
            : 'text-gray-400 hover:text-gray-200 hover:bg-gray-850'
        }"
      >
        SERP Competitor Rankings ({research.ranking_chart.length})
      </button>

      <button
        type="button"
        onclick={() => activeTab = 'keywords'}
        class="px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer {
          activeTab === 'keywords' 
            ? 'bg-indigo-600 text-white shadow-md shadow-indigo-500/10' 
            : 'text-gray-400 hover:text-gray-200 hover:bg-gray-850'
        }"
      >
        Tags & Related Keywords ({research.suggested_tags.length})
      </button>
    </div>

    <!-- Tab 1: Live Packaging & Mobile Viewport Simulator -->
    {#if activeTab === 'packaging'}
      <div class="space-y-5">
        
        <!-- Live Mobile Viewport Simulator Card -->
        <div class="p-5 rounded-2xl bg-gradient-to-r from-gray-900 via-gray-900/90 to-gray-950 border border-gray-800 shadow-xl space-y-4">
          <div class="flex items-center justify-between">
            <div class="flex items-center space-x-2">
              <Smartphone class="w-4 h-4 text-indigo-400" />
              <h3 class="text-xs font-bold text-white uppercase tracking-wider">
                Mobile Viewport Simulation (First 45 Characters Truncation)
              </h3>
            </div>
            <span class="text-[10px] font-mono text-gray-400">
              {selectedTitle.length} characters
            </span>
          </div>

          <!-- Mobile App Feed Mock Card -->
          <div class="p-4 rounded-xl bg-gray-950 border border-gray-800 max-w-lg space-y-3 shadow-inner">
            <div class="flex items-center space-x-2 text-[10px] font-mono text-gray-500">
              <span class="w-2 h-2 rounded-full bg-emerald-500"></span>
              <span>YouTube Mobile Feed Appearance</span>
            </div>
            
            <div class="space-y-1">
              <!-- Visual highlight of the first 45 chars -->
              <p class="text-sm font-bold text-white leading-snug">
                <span class="text-indigo-300 underline decoration-indigo-500/50 decoration-2 underline-offset-4">
                  {selectedTitle.slice(0, 45)}
                </span>
                <span class="text-gray-500">
                  {selectedTitle.length > 45 ? selectedTitle.slice(45) : ''}
                </span>
              </p>
              <span class="text-[10px] text-gray-500 block pt-1">
                Underlined portion is guaranteed visible on mobile screens before feed truncation.
              </span>
            </div>
          </div>
        </div>

        <!-- High-CTR Title Suggestion -->
        <div class="p-5 rounded-2xl bg-gray-900/60 border border-gray-800 space-y-3">
          <div class="flex items-center justify-between">
            <span class="text-xs font-bold text-indigo-400 uppercase tracking-wider flex items-center space-x-1.5">
              <Sparkles class="w-3.5 h-3.5" />
              <span>Active Packaging Title (Zero-Colon Rule Enforced)</span>
            </span>
            <div class="flex items-center space-x-2">
              <button 
                type="button" 
                onclick={() => copyToClipboard(selectedTitle)}
                class="text-xs text-gray-400 hover:text-white flex items-center space-x-1 cursor-pointer"
              >
                <Copy class="w-3.5 h-3.5" />
                <span>{copiedText === selectedTitle ? 'Copied!' : 'Copy Title'}</span>
              </button>
            </div>
          </div>

          <div class="flex items-center space-x-2">
            <input 
              type="text" 
              bind:value={selectedTitle}
              class="w-full text-base font-extrabold text-white font-mono bg-gray-950/80 p-3.5 rounded-xl border border-gray-800 focus:outline-none focus:border-indigo-500"
            />
          </div>
        </div>

        <!-- Recommended Tags Cloud -->
        {#if research.packaging.tags && research.packaging.tags.length > 0}
          <div class="p-5 rounded-2xl bg-gray-900/60 border border-gray-800 space-y-3">
            <div class="flex items-center justify-between">
              <span class="text-xs font-bold text-emerald-400 uppercase tracking-wider flex items-center space-x-1.5">
                <Tag class="w-3.5 h-3.5" />
                <span>Optimized Tag Set ({research.packaging.tags.length} Tags)</span>
              </span>
              <button 
                type="button" 
                onclick={() => copyToClipboard(research.packaging.tags.join(', '))}
                class="text-xs text-gray-400 hover:text-white flex items-center space-x-1 cursor-pointer"
              >
                <Copy class="w-3.5 h-3.5" />
                <span>Copy All</span>
              </button>
            </div>
            <div class="flex flex-wrap gap-2">
              {#each research.packaging.tags as tag}
                <button
                  type="button"
                  onclick={() => copyToClipboard(tag)}
                  class="px-3 py-1.5 rounded-xl text-xs bg-gray-950/80 border border-gray-800 hover:border-indigo-500 text-gray-300 hover:text-white transition-all cursor-pointer"
                >
                  {tag}
                </button>
              {/each}
            </div>
          </div>
        {/if}

        <!-- Description Blueprint -->
        <div class="p-5 rounded-2xl bg-gray-900/60 border border-gray-800 space-y-3">
          <div class="flex items-center justify-between">
            <span class="text-xs font-bold text-purple-400 uppercase tracking-wider flex items-center space-x-1.5">
              <FileText class="w-3.5 h-3.5" />
              <span>Description Blueprint (StoryBrand Problem ➔ Architecture Guide)</span>
            </span>
            <button 
              type="button" 
              onclick={() => copyToClipboard(research.packaging.description)}
              class="text-xs text-gray-400 hover:text-white flex items-center space-x-1 cursor-pointer"
            >
              <Copy class="w-3.5 h-3.5" />
              <span>Copy Description</span>
            </button>
          </div>
          <pre class="text-xs text-gray-300 font-mono bg-gray-950/80 p-4 rounded-xl border border-gray-800 whitespace-pre-wrap leading-relaxed">
{research.packaging.description}
          </pre>
        </div>

      </div>
    {/if}

    <!-- Tab 2: 4 Empirical Title Archetypes -->
    {#if activeTab === 'variations'}
      <div class="space-y-4">
        <div class="p-4 rounded-xl bg-gray-950/60 border border-gray-800 text-xs text-gray-400">
          Pick from 4 research-backed packaging formulas tested for maximum CTR and cognitive retention.
        </div>

        {#if research.packaging.title_variations && research.packaging.title_variations.length > 0}
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            {#each research.packaging.title_variations as varItem}
              <div class="p-5 rounded-2xl bg-gray-950/80 border {selectedTitle === varItem.title ? 'border-indigo-500 shadow-lg shadow-indigo-500/10' : 'border-gray-800'} space-y-3 flex flex-col justify-between">
                
                <div class="space-y-2">
                  <div class="flex items-center justify-between">
                    <span class="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                      {varItem.archetype}
                    </span>
                    {#if selectedTitle === varItem.title}
                      <span class="text-[10px] font-mono text-emerald-400 font-bold flex items-center space-x-1">
                        <Check class="w-3 h-3" />
                        <span>ACTIVE SELECTION</span>
                      </span>
                    {/if}
                  </div>

                  <h4 class="text-sm font-extrabold text-white font-mono leading-snug">
                    {varItem.title}
                  </h4>

                  <p class="text-xs text-gray-400 leading-relaxed">
                    {varItem.rationale}
                  </p>
                </div>

                <div class="pt-3 border-t border-gray-900 flex items-center justify-between">
                  <span class="text-[10px] font-mono text-gray-500">
                    Mobile: <span class="text-gray-300 font-semibold">{varItem.mobile_preview_45}</span>
                  </span>

                  <div class="flex items-center space-x-2">
                    <button
                      type="button"
                      onclick={() => selectedTitle = varItem.title}
                      class="px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer {
                        selectedTitle === varItem.title 
                          ? 'bg-emerald-600 text-white' 
                          : 'bg-gray-800 hover:bg-gray-700 text-gray-200'
                      }"
                    >
                      {selectedTitle === varItem.title ? 'Selected' : 'Use Title'}
                    </button>
                  </div>
                </div>

              </div>
            {/each}
          </div>
        {/if}
      </div>
    {/if}

    <!-- Tab 3: SERP Competitor Rankings Grid -->
    {#if activeTab === 'serp'}
      <div class="space-y-4">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          {#each research.ranking_chart as item}
            <div class="p-4 rounded-xl bg-gray-950/80 border border-gray-800 space-y-3 flex flex-col justify-between">
              
              <div class="space-y-2">
                <div class="flex items-center justify-between text-xs font-mono">
                  <span class="px-2 py-0.5 rounded-md bg-indigo-500/20 text-indigo-300 font-bold">
                    #{item.position} SERP
                  </span>
                  <span class="text-emerald-400 font-bold">
                    {item.views.toLocaleString()} views
                  </span>
                </div>

                <h4 class="text-sm font-bold text-gray-100 line-clamp-2">
                  {item.title}
                </h4>
              </div>

              <div class="flex items-center justify-between pt-2 border-t border-gray-900 text-xs font-mono text-gray-400">
                <span class="truncate max-w-[180px]">{item.channel}</span>
                <span class="px-2 py-0.5 rounded bg-gray-900 text-gray-400 text-[10px]">
                  SEO: {item.seo_score.toFixed(1)}
                </span>
              </div>

            </div>
          {/each}
        </div>
      </div>
    {/if}

    <!-- Tab 4: Tags & Related Keywords -->
    {#if activeTab === 'keywords'}
      <div class="space-y-5">
        
        <!-- Suggested Tags with Frequency -->
        <div class="p-5 rounded-2xl bg-gray-900/60 border border-gray-800 space-y-3">
          <h3 class="text-xs font-bold text-emerald-400 uppercase tracking-wider flex items-center space-x-2">
            <Tag class="w-3.5 h-3.5" />
            <span>High-Frequency Competitor Tags</span>
          </h3>
          <div class="flex flex-wrap gap-2 pt-1">
            {#each research.suggested_tags as item}
              <button
                type="button"
                onclick={() => copyToClipboard(item.tag)}
                class="px-3 py-1.5 rounded-xl text-xs bg-gray-950/80 border border-gray-800 hover:border-emerald-500 text-gray-300 hover:text-emerald-300 transition-all flex items-center space-x-1.5 cursor-pointer group"
              >
                <span>{item.tag}</span>
                <span class="text-[10px] font-mono text-gray-500 group-hover:text-emerald-400">
                  ({item.usage}x)
                </span>
              </button>
            {/each}
          </div>
        </div>

        <!-- Related Keywords from Autocomplete -->
        {#if research.related_keywords && research.related_keywords.length > 0}
          <div class="p-5 rounded-2xl bg-gray-900/60 border border-gray-800 space-y-3">
            <h3 class="text-xs font-bold text-purple-400 uppercase tracking-wider flex items-center space-x-2">
              <TrendingUp class="w-3.5 h-3.5" />
              <span>Related Search Queries (Autocomplete Order)</span>
            </h3>
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
              {#each research.related_keywords as item}
                <div class="p-3 rounded-xl bg-gray-950/80 border border-gray-800 flex items-center justify-between text-xs">
                  <span class="text-gray-200 font-mono">{item.keyword}</span>
                  <span class="px-2 py-0.5 rounded bg-purple-500/10 text-purple-400 font-mono text-[10px]">
                    Rank #{item.popularity_rank}
                  </span>
                </div>
              {/each}
            </div>
          </div>
        {/if}

      </div>
    {/if}

  {/if}

</div>
